//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEF.ConsoleApp.TEST.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICommon")]
    public interface ICommon {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/GetVoucher", ReplyAction="http://tempuri.org/ICommon/GetVoucherResponse")]
        string GetVoucher(string quoteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/SingnedVoucher", ReplyAction="http://tempuri.org/ICommon/SingnedVoucherResponse")]
        string SingnedVoucher(string new_paymentid, string new_type, string new_itype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/CloseQuoteRequest", ReplyAction="http://tempuri.org/ICommon/CloseQuoteRequestResponse")]
        string CloseQuoteRequest(string quoteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/Muhasebelestir", ReplyAction="http://tempuri.org/ICommon/MuhasebelestirResponse")]
        string Muhasebelestir(string quoteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommon/ContractSigned", ReplyAction="http://tempuri.org/ICommon/ContractSignedResponse")]
        string ContractSigned(string quoteId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonChannel : NEF.ConsoleApp.TEST.ServiceReference1.ICommon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonClient : System.ServiceModel.ClientBase<NEF.ConsoleApp.TEST.ServiceReference1.ICommon>, NEF.ConsoleApp.TEST.ServiceReference1.ICommon {
        
        public CommonClient() {
        }
        
        public CommonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVoucher(string quoteId) {
            return base.Channel.GetVoucher(quoteId);
        }
        
        public string SingnedVoucher(string new_paymentid, string new_type, string new_itype) {
            return base.Channel.SingnedVoucher(new_paymentid, new_type, new_itype);
        }
        
        public string CloseQuoteRequest(string quoteId) {
            return base.Channel.CloseQuoteRequest(quoteId);
        }
        
        public string Muhasebelestir(string quoteId) {
            return base.Channel.Muhasebelestir(quoteId);
        }
        
        public string ContractSigned(string quoteId) {
            return base.Channel.ContractSigned(quoteId);
        }
    }
}
