//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEF.ConsoleApp.SendCampaignActivityEmail.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.euromsg.com/liveb/auth.asmx")]
        public string Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_auth_Auth {
            get {
                return ((string)(this["Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_auth_Auth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.euromsg.com/liveb/campaign.asmx")]
        public string Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_campaign_Campaign {
            get {
                return ((string)(this["Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_campaign_Campaign"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.euromsg.com/liveb/sendlist.asmx")]
        public string Nef_ConsoleApp_SendCampaignActivityEmail_sendlist_SendList {
            get {
                return ((string)(this["Nef_ConsoleApp_SendCampaignActivityEmail_sendlist_SendList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.euromsg.com/liveb/report.asmx")]
        public string Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_report_Report {
            get {
                return ((string)(this["Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_report_Report"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.euromsg.com/live/campaign.asmx")]
        public string Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_campaign_live_Campaign {
            get {
                return ((string)(this["Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_campaign_live_Campaign"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.euromsg.com/live/auth.asmx")]
        public string Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_auth_live_Auth {
            get {
                return ((string)(this["Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_auth_live_Auth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.euromsg.com/live/sendlist.asmx")]
        public string Nef_ConsoleApp_SendCampaignActivityEmail_sendlist_live_SendList {
            get {
                return ((string)(this["Nef_ConsoleApp_SendCampaignActivityEmail_sendlist_live_SendList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws.euromsg.com/live/report.asmx")]
        public string Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_report_live_Report {
            get {
                return ((string)(this["Nef_ConsoleApp_SendCampaignActivityEmail_com_euromsg_report_live_Report"]));
            }
        }
    }
}
