//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEF.ConsoleApp.TEST.test2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="test2.IIntegration")]
    public interface IIntegration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegration/GetContactDetail2", ReplyAction="http://tempuri.org/IIntegration/GetContactDetail2Response")]
        NEF.Library.Utility.Contact GetContactDetail2(System.Guid contactId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegrationChannel : NEF.ConsoleApp.TEST.test2.IIntegration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntegrationClient : System.ServiceModel.ClientBase<NEF.ConsoleApp.TEST.test2.IIntegration>, NEF.ConsoleApp.TEST.test2.IIntegration {
        
        public IntegrationClient() {
        }
        
        public IntegrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntegrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntegrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NEF.Library.Utility.Contact GetContactDetail2(System.Guid contactId) {
            return base.Channel.GetContactDetail2(contactId);
        }
    }
}
