//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEF.ConsoleApp.MobilWebServisTest.FenixMobilService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FenixMobilService.IMobilService")]
    public interface IMobilService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/Login", ReplyAction="http://tempuri.org/IMobilService/LoginResponse")]
        string Login(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/Login", ReplyAction="http://tempuri.org/IMobilService/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/GetPaymentList", ReplyAction="http://tempuri.org/IMobilService/GetPaymentListResponse")]
        string GetPaymentList(string customerId, NEF.WebService.MobilApp.CustomerType customerType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/GetPaymentList", ReplyAction="http://tempuri.org/IMobilService/GetPaymentListResponse")]
        System.Threading.Tasks.Task<string> GetPaymentListAsync(string customerId, NEF.WebService.MobilApp.CustomerType customerType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/GetProject", ReplyAction="http://tempuri.org/IMobilService/GetProjectResponse")]
        string GetProject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/GetProject", ReplyAction="http://tempuri.org/IMobilService/GetProjectResponse")]
        System.Threading.Tasks.Task<string> GetProjectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/GetCustomer", ReplyAction="http://tempuri.org/IMobilService/GetCustomerResponse")]
        string GetCustomer(int page, int rowCount, NEF.WebService.MobilApp.CustomerType customerType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/GetCustomer", ReplyAction="http://tempuri.org/IMobilService/GetCustomerResponse")]
        System.Threading.Tasks.Task<string> GetCustomerAsync(int page, int rowCount, NEF.WebService.MobilApp.CustomerType customerType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/GetFoldhome", ReplyAction="http://tempuri.org/IMobilService/GetFoldhomeResponse")]
        string GetFoldhome(string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/GetFoldhome", ReplyAction="http://tempuri.org/IMobilService/GetFoldhomeResponse")]
        System.Threading.Tasks.Task<string> GetFoldhomeAsync(string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/CreateFoldhome", ReplyAction="http://tempuri.org/IMobilService/CreateFoldhomeResponse")]
        string CreateFoldhome(NEF.WebService.MobilApp.Foldhome foldhome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/CreateFoldhome", ReplyAction="http://tempuri.org/IMobilService/CreateFoldhomeResponse")]
        System.Threading.Tasks.Task<string> CreateFoldhomeAsync(NEF.WebService.MobilApp.Foldhome foldhome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/UpdateFoldhome", ReplyAction="http://tempuri.org/IMobilService/UpdateFoldhomeResponse")]
        string UpdateFoldhome(NEF.WebService.MobilApp.Foldhome foldhome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/UpdateFoldhome", ReplyAction="http://tempuri.org/IMobilService/UpdateFoldhomeResponse")]
        System.Threading.Tasks.Task<string> UpdateFoldhomeAsync(NEF.WebService.MobilApp.Foldhome foldhome);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/CreateWebForm", ReplyAction="http://tempuri.org/IMobilService/CreateWebFormResponse")]
        string CreateWebForm(NEF.WebService.MobilApp.WebCustomerInfo WebCustomerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/CreateWebForm", ReplyAction="http://tempuri.org/IMobilService/CreateWebFormResponse")]
        System.Threading.Tasks.Task<string> CreateWebFormAsync(NEF.WebService.MobilApp.WebCustomerInfo WebCustomerInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/CreateLead", ReplyAction="http://tempuri.org/IMobilService/CreateLeadResponse")]
        string CreateLead(NEF.WebService.MobilApp.LeadInfo LeadInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/CreateLead", ReplyAction="http://tempuri.org/IMobilService/CreateLeadResponse")]
        System.Threading.Tasks.Task<string> CreateLeadAsync(NEF.WebService.MobilApp.LeadInfo LeadInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/GetMobilAppCustomer", ReplyAction="http://tempuri.org/IMobilService/GetMobilAppCustomerResponse")]
        string GetMobilAppCustomer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobilService/GetMobilAppCustomer", ReplyAction="http://tempuri.org/IMobilService/GetMobilAppCustomerResponse")]
        System.Threading.Tasks.Task<string> GetMobilAppCustomerAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMobilServiceChannel : NEF.ConsoleApp.MobilWebServisTest.FenixMobilService.IMobilService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobilServiceClient : System.ServiceModel.ClientBase<NEF.ConsoleApp.MobilWebServisTest.FenixMobilService.IMobilService>, NEF.ConsoleApp.MobilWebServisTest.FenixMobilService.IMobilService {
        
        public MobilServiceClient() {
        }
        
        public MobilServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobilServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobilServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobilServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string emailAddress) {
            return base.Channel.Login(emailAddress);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string emailAddress) {
            return base.Channel.LoginAsync(emailAddress);
        }
        
        public string GetPaymentList(string customerId, NEF.WebService.MobilApp.CustomerType customerType) {
            return base.Channel.GetPaymentList(customerId, customerType);
        }
        
        public System.Threading.Tasks.Task<string> GetPaymentListAsync(string customerId, NEF.WebService.MobilApp.CustomerType customerType) {
            return base.Channel.GetPaymentListAsync(customerId, customerType);
        }
        
        public string GetProject() {
            return base.Channel.GetProject();
        }
        
        public System.Threading.Tasks.Task<string> GetProjectAsync() {
            return base.Channel.GetProjectAsync();
        }
        
        public string GetCustomer(int page, int rowCount, NEF.WebService.MobilApp.CustomerType customerType) {
            return base.Channel.GetCustomer(page, rowCount, customerType);
        }
        
        public System.Threading.Tasks.Task<string> GetCustomerAsync(int page, int rowCount, NEF.WebService.MobilApp.CustomerType customerType) {
            return base.Channel.GetCustomerAsync(page, rowCount, customerType);
        }
        
        public string GetFoldhome(string customerId) {
            return base.Channel.GetFoldhome(customerId);
        }
        
        public System.Threading.Tasks.Task<string> GetFoldhomeAsync(string customerId) {
            return base.Channel.GetFoldhomeAsync(customerId);
        }
        
        public string CreateFoldhome(NEF.WebService.MobilApp.Foldhome foldhome) {
            return base.Channel.CreateFoldhome(foldhome);
        }
        
        public System.Threading.Tasks.Task<string> CreateFoldhomeAsync(NEF.WebService.MobilApp.Foldhome foldhome) {
            return base.Channel.CreateFoldhomeAsync(foldhome);
        }
        
        public string UpdateFoldhome(NEF.WebService.MobilApp.Foldhome foldhome) {
            return base.Channel.UpdateFoldhome(foldhome);
        }
        
        public System.Threading.Tasks.Task<string> UpdateFoldhomeAsync(NEF.WebService.MobilApp.Foldhome foldhome) {
            return base.Channel.UpdateFoldhomeAsync(foldhome);
        }
        
        public string CreateWebForm(NEF.WebService.MobilApp.WebCustomerInfo WebCustomerInfo) {
            return base.Channel.CreateWebForm(WebCustomerInfo);
        }
        
        public System.Threading.Tasks.Task<string> CreateWebFormAsync(NEF.WebService.MobilApp.WebCustomerInfo WebCustomerInfo) {
            return base.Channel.CreateWebFormAsync(WebCustomerInfo);
        }
        
        public string CreateLead(NEF.WebService.MobilApp.LeadInfo LeadInfo) {
            return base.Channel.CreateLead(LeadInfo);
        }
        
        public System.Threading.Tasks.Task<string> CreateLeadAsync(NEF.WebService.MobilApp.LeadInfo LeadInfo) {
            return base.Channel.CreateLeadAsync(LeadInfo);
        }
        
        public string GetMobilAppCustomer() {
            return base.Channel.GetMobilAppCustomer();
        }
        
        public System.Threading.Tasks.Task<string> GetMobilAppCustomerAsync() {
            return base.Channel.GetMobilAppCustomerAsync();
        }
    }
}
